name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildAndTest:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13.3]
        otp: [23.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Setup Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Install dependencies and compile
        run: mix do deps.get, deps.compile
      - name: Run test
        run: mix test 
      - name: Check Formatting
        run: mix format --check-formatted